### ISSUE TITLE
Clean up usage of populate method

### ISSUE THREAD

**Issue by MartyWallace** [MartyWallace/simpledb#4]
At the moment you cannot just assume this will work:

    $db->table('table')->find(1)->populate(Thing::class);

As `find()` could return `null`.

Investigate cleaner solution.

**Comment by DmitriyLanchakov** [comment]
```
use SimpleDb\Database;
$db = new Database('root:password@localhost/vokuro');
$db->table('user')->find(1)->populate(User::class);
```

The table 'user' is not empty.
Fatal error:  Uncaught Error: Call to a member function populate() on null

Also I did not find this function 'populate' in your source.

**Comment by martywallace** [comment]
@DmitriyLanchakov This functionality exists in the [`2.x` releases](https://github.com/MartyWallace/simpledb/releases/tag/2.2.1). There is no written guide for the 3.x release set yet but your example would be done like:

```
$db = new Database('root:password@localhost/vokuro');

$user = User::find(1); // or
$user = User::from($db->table('users')->find(1));
```
